### PR TITLE
Add tests for com.vladsch.flexmark.util.Utils and describe bugs

### PR DESCRIPTION
**Pull request by James-Adam**
Hi,
I've analysed your codebase and seen some parts of com.vladsch.flexmark.util.Utils are not yet tested.

I've written the tests for the functions in Utils.java with the help of [Diffblue Cover](https://www.diffblue.com/products). 
While working on producing these tests, I noticed some current behaviours in these functions that appear to be incorrect. Tests which describe such behaviour have been clearly marked with comments explaining why they appear to be incorrect, and what output we should expect if the function was behaving as intended. Please let me know whether you would like an additional PR to fix these behaviours. 

Hopefully these tests will help you to increase the quality of flexmark's test suite. If you have any other classes you'd like help writing tests for, please let me know.

### CODE REVIEW

**Comment by vsch** [comment]
@James-Adam, much appreciated. I simply have not had time to address all tests. I wish I could focus on this and a few other projects without having to distract myself with earning a living. ;)

I will merge your tests and take a look at the incorrect behaviour which is most likely bugs.

**Comment by James-Adam** [comment]
@vsch Not a problem! If you have any questions regarding the tests or the behaviours I have flagged as potentially being bugs, feel free to get in touch!

**Comment by vsch** [comment]
@James-Adam, can confirm the bugs. I fixed all the detected bugs and updated the tests to reflect correct operation. 

The wrapWith was completely screwed up. Prefix was being added as suffix.

Thank you very much. The fixes and test will be part of the next release.

**Comment by vsch** [comment]
@James-Adam, thank you and your comments were succinct and clear. I also changed some tests for wrapWith because the implementation was off the wall wrong. I threw it in for completeness but lucky for me did not use it anywhere.

I will be refactoring the code to eliminate a lot of the duplicate Utils String implementation into a reusable String/CharSequence that can be shared with BasedSequence so all these extra functions have a common tested implementation. 

BasedSequence morphed over time to include a lot of untested methods which I need to address and would like to do it in a re-usable interface with default implementations to allow including `implements RichCharSequence` for example, adding most of the functionality with minimal implementation, if any, by the class.

**Comment by vsch** [comment]
BTW, I pushed the changed Utils and  UtilsTest to the master branch.

**Pull request merged**
