### PR TITLE
Implemented extension media-tags

### PR DESCRIPTION
**Pull request by CorneliaXaos**
* Updated various project files
* Created module for media tags extension
* Created skeleton extension class
* Created test cases using the AST spec approach
* Refined AST specs for correct expectation
* EmbedLinks function correctly
* Extracted some code that will be common to many node types
* AudioLink node functions correctly
* Refactored code to reduce duplication
* PictureLink node renders correctly
* VideoLinks function correctly
* Added test cases for escaped prefixes
* Altered specification for default prefixes
* Updated logic to support new prefixes and allow escaping
* Project files upgrades (again)
* Fixed project-breaking refactor
* Added basic Javadoc

### CODE REVIEW

**Comment by CorneliaXaos** [comment]
I feel silly having done so many revisions for the pull requests, etc.. but.. first time contributing something this big to another project. :P

**Comment by CorneliaXaos** [comment]
Oh...  The checks fails because I added flexmark-ext-media-tags to the flexmark-all pom file...  *sigh*  Will wait for feedback before I do anything..

**Comment by CorneliaXaos** [comment]
Also.. it seems some files got reverted some for some reason.. namely the Version.md seems off..

**Comment by vsch** [comment]
@CorneliaXaos, thank you for the PR. I will have to merge this and partially revert some files that appear to have been changed erroneously. Don't fret over it. I don't trust git 100%. I have had wrestling matches with git trying to fix changes for which I could not understand the source.

**Comment by CorneliaXaos** [comment]
Alrighty. Other than the Version.md file getting altered somehow a lot of changes appear to be automatically generated IntelliJ project files. I notice that the generated project files for each module are included in source control while JetBrains suggests they might ought not to be.

https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems
https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

Also, you'll see in several places Ithe SDK version was changed (by the IDE). This is because I don't / can't easily get a Java 7 SDK installed. I have a JDK8 instance and IntelliJ can use that to build Java 7 projects so it works.

**Comment by vsch** [comment]
@CorneliaXaos, thank you for the contribution. I changed the artifact to `flexmark-ext-media-tags` to match the rest of the extensions.

Repo updated. Maven central update in progress.

**Comment by CorneliaXaos** [comment]
Cool!  Also.. I thought I had the artifact named that...  At least.. that's what it's called on my machine..

Also, when would these end up in maven?  I'd like to have an idea of when I can actually pull them into a project proper.

**Comment by vsch** [comment]
@CorneliaXaos, maven is now reporting 0.34.4 so you can use it now.

**Pull request merged**
