### PR TITLE
Adding OSGi bundle support

### PR DESCRIPTION
**Pull request by klcodanr**
Currently, Flexmark does not provide support for installing as an [OSGi bundle](https://www.osgi.org/developer/architecture/). While it can be wrapped via another project, it would be great to directly provide OSGi support. This PR has a sub-project similar to the `flexmark-all` project to create an OSGi Bundle version of Flexmark.

I did exclude the PDF Converter as it drastically increases the dependencies and the `com.openhtmltopdf` library used is licensed under the LGPL which can be problematic to include in some projects.

### CODE REVIEW

**Comment by qwazer** [comment]
May be add the word `osgi` in module name? Because `flexmark-bundle` confuses with `flexmark` and 
`flexmark-all`

**Comment by klcodanr** [comment]
Good point @qwazer -- updated.

**Comment by ieugen** [comment]
How about using a property for the dependency versions? This should simplify upgrades.

Since flexmark-osgi dependencies have the same version as the project itself you could use ${project.version} for all dependencies.

**Comment by vsch** [comment]
@klcodanr, thank you.

Are you sure including the Docx converter is a good idea? For the same reason PDF is excluded. This module adds a lot of extra dependencies.

Also, project version variable is used for the dependencies but I did not see where it is defined. The module's dependency is still hard-coded.

The reason I did not change to all module pom files to use project version variable is I was not sure where to define the variable so it is available in all module pom files.

Instead I use `mvn versions:set -DnewVersion=0.x.x` to set version for all modules.

**Comment by vsch** [comment]
@ieugen, docx converter with dependencies is about 21MB without other flexmark-java extensions.

I think it makes sense to have docx and pdf converters as separate OSGi bundles.

**Comment by klcodanr** [comment]
@vsch & @ieugen - Looking more closely at the POM, `flexmark-docx-converter` is excluded from the `flexmark-all` as well as `flexmark-osgi`. The total OSGi Bundle / JAR size clocks in at 1.7MB.

**Comment by vsch** [comment]
@klcodanr, I will merge the PR and make a new release

**Comment by vsch** [comment]
@klcodanr, module merged, version updated to 0.34.22, maven update in progress.

Thank you very much for the initiative and the implementation.

**Comment by klcodanr** [comment]
Thanks for the quick response and support @vsch !

**Pull request merged**
